In [ ]:
import kagglehub

In [ ]:
local_dataset_path = kagglehub.dataset_download('irkaal/foodcom-recipes-and-reviews')

Using Colab cache for faster access to the 'foodcom-recipes-and-reviews' dataset.

In [ ]:
import pandas as pd
import matplotlib.pyplot as pl
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
import os
full_reviews_path = os.path.join(local_dataset_path, 'reviews.csv')
reviews = pd.read_csv(full_reviews_path)

In [ ]:
!pip install gdown

# ID del archivo de Google Drive
file_id = '1Rl8XowC9N6cxrdiPvH4wToFUvZrrBqRG'
output_filename = 'recipes_final_consolidado.csv'

# Descargar el archivo usando gdown
!gdown --id {file_id} -O {output_filename}

# Cargar el archivo CSV con pandas
recipes = pd.read_csv(output_filename)
recipes['ExtractedServingSize'] = recipes['ExtractedServingSize'].str.extract(r'\((.*?)\)').astype(float)

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.4.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)
/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1Rl8XowC9N6cxrdiPvH4wToFUvZrrBqRG
From (redirected): https://drive.google.com/uc?id=1Rl8XowC9N6cxrdiPvH4wToFUvZrrBqRG&confirm=t&uuid=af9c9b8d-2148-4a20-99ab-81908b7855c0
To: /content/recipes_final_consolidado.csv
100% 713M/713M [00:11<00:00, 61.9MB/s]

In [ ]:
# Filtrar la receta con ExtractedServingSize igual a -475.0
receta_anomala = recipes[recipes['ExtractedServingSize'] == -475.0]
display(receta_anomala)

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions,ExtractedServingSize,ExtractedServings,ExtractedServings_clean,ConsolidatedServings
16628,19962,Rainforest Cafe Rasta Pasta for Two or Three,10404,Diana Adcock,PT15M,PT5M,PT20M,2002-02-18T09:24:00Z,Make and share this Rainforest Cafe Rasta Past...,"""https://img.sndimg.com/food/image/upload/w_55...",...,7.2,4.8,19.7,2.0,NaN,"c(""Cook pasta according to package directions....",-475.0,2,2,2

In [ ]:
def get_stats(recipes, reviews):
  num_users = reviews['AuthorId'].nunique()
  num_items = recipes['RecipeId'].nunique()
  total_ratings = len(reviews)
  avg_ratings_per_user = total_ratings / num_users
  avg_ratings_per_item = total_ratings / num_items
  avg_rating = reviews['Rating'].mean()
  mode_rating = reviews['Rating'].mode()[0]
  std_rating = reviews['Rating'].std()
  highest_ratings_user = reviews.groupby('AuthorId')['Rating'].count().max()
  highest_ratings_item = reviews.groupby('RecipeId')['Rating'].count().max()
  density = (total_ratings / (num_users * num_items)) * 100
  return [
      num_users,
      num_items,
      total_ratings,
      round(avg_ratings_per_user, 2),
      round(avg_ratings_per_item, 2),
      round(avg_rating, 2),
      mode_rating,
      round(std_rating, 2),
      highest_ratings_user,
      highest_ratings_item,
      f"{density:.2f} %"
  ]

stats_names = [
    "Cantidad de usuarios",
    "Cantidad de recetas",
    "Total de ratings",
    "Número promedio de ratings por usuario",
    "Número promedio de ratings por recetas",
    "Rating promedio",
    "Rating Moda",
    "Desviación estándar de Rating",
    "Cantidad más alta de ratings de un usuario",
    "Cantidad más alta de ratings de una receta",
    "Densidad (%)"
]

todo_stats = get_stats(recipes, reviews)
#val_stats = get_stats(val_file)

summary_df = pd.DataFrame({
    'Estadísticas': stats_names,
    'Todo': todo_stats,
})

display(summary_df)

                                  Estadísticas     Todo
0                         Cantidad de usuarios   271907
1                          Cantidad de recetas   522359
2                             Total de ratings  1401982
3       Número promedio de ratings por usuario     5.16
4       Número promedio de ratings por recetas     2.68
5                              Rating promedio     4.41
6                                  Rating Moda        5
7                Desviación estándar de Rating     1.27
8   Cantidad más alta de ratings de un usuario     8842
9   Cantidad más alta de ratings de una receta     2892
10                                Densidad (%)   0.00 %

In [ ]:
recipe_counts = reviews['RecipeId'].value_counts()
little_review_recipes = recipe_counts[recipe_counts == 1]
len(little_review_recipes)
total_recipes = reviews['RecipeId'].nunique()
recipe_name = recipes[recipes['RecipeId'] == 363893]['Name'].iloc[0]
review_counts = reviews['AuthorId'].value_counts()
little_review_users = review_counts[review_counts == 1]

In [ ]:
def get_stats(recipes, reviews):
  num_users = reviews['AuthorId'].nunique()
  num_items = recipes['RecipeId'].nunique()
  total_ratings = len(reviews)
  avg_ratings_per_user = total_ratings / num_users
  avg_ratings_per_item = total_ratings / num_items
  avg_rating = reviews['Rating'].mean()
  mode_rating = reviews['Rating'].mode()[0]
  std_rating = reviews['Rating'].std()
  highest_ratings_user = reviews.groupby('AuthorId')['Rating'].count().max()
  highest_ratings_item = reviews.groupby('RecipeId')['Rating'].count().max()
  density = (total_ratings / (num_users * num_items)) * 100
  return [
      num_users,
      num_items,
      total_ratings,
      round(avg_ratings_per_user, 2),
      round(avg_ratings_per_item, 2),
      round(avg_rating, 2),
      mode_rating,
      round(std_rating, 2),
      highest_ratings_user,
      highest_ratings_item,
      f"{density:.2f} %"
  ]

stats_names = [
    "Cantidad de usuarios",
    "Cantidad de recetas",
    "Total de ratings",
    "Número promedio de ratings por usuario",
    "Número promedio de ratings por recetas",
    "Rating promedio",
    "Rating Moda",
    "Desviación estándar de Rating",
    "Cantidad más alta de ratings de un usuario",
    "Cantidad más alta de ratings de una receta",
    "Densidad (%)"
]

todo_stats = get_stats(recipes, reviews)
#val_stats = get_stats(val_file)

summary_df = pd.DataFrame({
    'Estadísticas': stats_names,
    'Todo': todo_stats,
})

display(summary_df)

                                  Estadísticas     Todo
0                         Cantidad de usuarios   271907
1                          Cantidad de recetas   522359
2                             Total de ratings  1401982
3       Número promedio de ratings por usuario     5.16
4       Número promedio de ratings por recetas     2.68
5                              Rating promedio     4.41
6                                  Rating Moda        5
7                Desviación estándar de Rating     1.27
8   Cantidad más alta de ratings de un usuario     8842
9   Cantidad más alta de ratings de una receta     2892
10                                Densidad (%)   0.00 %

In [ ]:
# Estadísticas tras recorte/filtración

reviews_filtrado = reviews[~reviews['AuthorId'].isin(little_review_users.index)]
# reviews_filtrado = reviews_filtrado[~reviews_filtrado['RecipeId'].isin(little_review_recipes.index)]
recipes_filtrado = recipes[recipes['RecipeId'].isin(reviews_filtrado['RecipeId'].unique())]

filtrado_stats = get_stats(recipes_filtrado, reviews_filtrado)

summary_df = pd.DataFrame({
    'Estadísticas': stats_names,
    'Todo': todo_stats,
    'Filtrado': filtrado_stats,
})

display(summary_df)

                                  Estadísticas     Todo Filtrado
0                         Cantidad de usuarios   271907    72099
1                          Cantidad de recetas   522359   258314
2                             Total de ratings  1401982  1202174
3       Número promedio de ratings por usuario     5.16    16.67
4       Número promedio de ratings por recetas     2.68     4.65
5                              Rating promedio     4.41     4.52
6                                  Rating Moda        5        5
7                Desviación estándar de Rating     1.27     1.07
8   Cantidad más alta de ratings de un usuario     8842     8842
9   Cantidad más alta de ratings de una receta     2892     2359
10                                Densidad (%)   0.00 %   0.01 %

In [ ]:
import numpy as np
import heapq
from sklearn.metrics import pairwise_distances
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import time

In [ ]:
# Metricas
def precision_at_k(r, k):
    assert k >= 1
    r = np.asarray(r)[:k] != 0
    if r.size != k:
        raise ValueError('Relevance score length < k')
    return np.mean(r)

def average_precision(r):
    r = np.asarray(r) != 0
    out = [precision_at_k(r, k + 1) for k in range(r.size) if r[k]]
    if not out:
        return 0.
    return np.mean(out)

def mean_average_precision(rs):
    return np.mean([average_precision(r) for r in rs])

def dcg_at_k(r, k):
    r = np.asarray(r)[:k]
    if r.size:
        return np.sum(np.subtract(np.power(2, r), 1) / np.log2(np.arange(2, r.size + 2)))
    return 0.

def ndcg_at_k(r, k):
    idcg = dcg_at_k(sorted(r, reverse=True), k)
    if not idcg:
        return 0.
    return dcg_at_k(r, k) / idcg

In [ ]:
# Funciones sacadas directamente del practico
def find_similar_recipes(embedding, query_id=None, metric='cosine', topk=10):
    n = embedding.shape[0]
    if query_id is None:
        query_i = np.random.randint(n)
        query_id = idx2recipeid[query_i]
    else:
        query_i = recipeid2idx[query_id]
    distances = pairwise_distances(embedding[query_i].reshape(1,-1), embedding, metric=metric)
    heap = []
    for i in range(n):
        if len(heap) < topk:
            heapq.heappush(heap, (-distances[0][i], i))
        else:
            heapq.heappushpop(heap, (-distances[0][i], i))
    heap.sort(reverse=True)
    return [idx2recipeid[i] for _, i in heap]

def recommend(embedding, user_id=None, topk=10, metric='cosine'):
    user_id = str(user_id)
    trx = user_interactions[user_id]
    n = embedding.shape[0]
    distances = 1e9
    for t in trx:
        if t not in recipeid2idx:
            continue
        query_i = recipeid2idx[t]
        distances = np.minimum(distances, pairwise_distances(
            embedding[query_i].reshape(1,-1), embedding, metric=metric).reshape(-1))
    trx_set = set(trx)
    heap = []
    for i in range(n):
        if idx2recipeid[i] in trx_set:
            continue
        if len(heap) < topk:
            heapq.heappush(heap, (-distances[i], i))
        else:
            heapq.heappushpop(heap, (-distances[i], i))
    heap.sort(reverse=True)
    return [idx2recipeid[i] for _, i in heap]

In [ ]:
# Mapeo con el data set completo
recipes['text'] = recipes['Name'].fillna('') + ' ' + recipes['Description'].fillna('')

vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
tfidf_sparse = vectorizer.fit_transform(recipes['text'])
tfidf_featmat = TruncatedSVD(n_components=50, random_state=42).fit_transform(tfidf_sparse)

print("Forma de la matriz de características:", tfidf_featmat.shape)

idx2recipeid = {i: id_ for i, id_ in enumerate(recipes['RecipeId'])}
recipeid2idx = {id_: i for i, id_ in idx2recipeid.items()}

reviews_sorted = reviews.sort_values('DateSubmitted')
user_interactions = {}
user_interactions_test = {}
for user_id, group in reviews_sorted.groupby('AuthorId'):
    items = group['RecipeId'].tolist()
    if len(items) < 2:
        continue
    user_interactions[str(user_id)] = items[:-1]
    user_interactions_test[str(user_id)] = [items[-1]]

print(f"Usuarios train: {len(user_interactions)}")
print(f"Usuarios test:  {len(user_interactions_test)}")

Forma de la matriz de características: (522359, 50)
Usuarios train: 72099
Usuarios test:  72099

In [ ]:
test_users = list(user_interactions_test.keys())[:100]
start = time.time()
mean_map, mean_ndcg = 0., 0.
mean_precision, mean_recall = 0., 0.  # +
topk = 10

for i, u in enumerate(test_users):
    print(i, end='\r')
    rec = recommend(tfidf_featmat, user_id=u, topk=topk)
    rel_vector = [np.isin(user_interactions_test[u], rec, assume_unique=True).astype(int)]
    mean_map += mean_average_precision(rel_vector)
    mean_ndcg += ndcg_at_k(rel_vector, topk)
    hits = rel_vector[0].sum()                          # +
    mean_precision += hits / topk                       # +
    mean_recall += hits / len(user_interactions_test[u])# +

mean_map /= len(test_users)
mean_ndcg /= len(test_users)
mean_precision /= len(test_users)  # +
mean_recall /= len(test_users)     # +

print('--- Dataset completo ---')  # (o "filtrado" según el bloque)
print('MAP ', mean_map)
print('ndcg@10', mean_ndcg)
print('precision@10', round(mean_precision, 4))  # +
print('recall@10', round(mean_recall, 4))         # +
print('tiempo de ejecucion {0:.2f} segs'.format(time.time() - start))

--- Dataset completo ---
MAP  0.01
ndcg@10 0.01
precision@10 0.001
recall@10 0.01
tiempo de ejecucion 2207.97 segs